# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
    required_providers {
        hcloud = {
            source = "hetznercloud/hcloud"
        }
    }
}

variable "hcloud_token" {
    default = ""
    sensitive = true
}
provider "hcloud" {
    token = var.hcloud_token
}
